export type Role = "user" | "assistant" | "tool" | "system";

/** "trace" rows are intermediate agent breadcrumbs (tool-call hints,
 * progress pings) that should not be rendered as conversational replies. */
export type MessageKind = "message" | "trace";

/** One image attached to a UIMessage.
 *
 * ``url`` can arrive in three different shapes, which the bubble renders
 * identically:
 * - A ``data:image/...;base64,...`` URL generated by the Composer for the
 *   optimistic preview of an in-flight user turn. Self-contained, no
 *   lifecycle.
 * - A signed ``/api/media/...`` URL attached to a historical user turn by
 *   the backend on session replay. Safe to drop into an ``<img src>``.
 * - Absent. The backend couldn't resolve a stored path (file moved,
 *   deleted, or pre-media-persistence session). The bubble shows a
 *   placeholder tile with ``name`` as the label.
 */
export interface UIImage {
  url?: string;
  name?: string;
}

export type UIMediaKind = "image" | "video" | "audio" | "file";

export interface UIMediaAttachment {
  kind: UIMediaKind;
  url?: string;
  name?: string;
}

export interface UIMessage {
  id: string;
  role: Role;
  content: string;
  kind?: MessageKind;
  isStreaming?: boolean;
  createdAt: number;
  /** For trace rows: each individual hint line, so consecutive hints can
   * render as a single collapsible group. */
  traces?: string[];
  /** Structured tool progress events used for live activity summaries. */
  toolEvents?: ToolProgressEvent[];
  /** User turn: optimistic blob URLs for preview. Replay: placeholder chips. */
  images?: UIImage[];
  /** Signed or local UI-renderable media attachments. */
  media?: UIMediaAttachment[];
  /** Assistant turn: accumulated model reasoning / thinking text. Built up
   * incrementally from ``reasoning_delta`` frames; finalized when
   * ``reasoning_end`` arrives. */
  reasoning?: string;
  /** True while ``reasoning_delta`` frames are still arriving for this turn.
   * Drives the shimmer header on ``ReasoningBubble``. */
  reasoningStreaming?: boolean;
  /** End-to-end wall time for this assistant turn (persisted ``latency_ms`` / ``turn_end``). */
  latencyMs?: number;
  /** Optional answer choices for a pending OriginAgent confirmation/question. */
  buttons?: string[][];
}

/** Structured UI blob on ``progress`` WS frames; channels may add more ``kind`` values later. */
export interface AgentUIBlob {
  kind: string;
  data?: unknown;
}

/** WebSocket snapshot for sustained goals (`goal_state` events; keyed by ``chat_id``). */
export interface GoalStateWsPayload {
  active: boolean;
  ui_summary?: string;
  objective?: string;
}

export interface ToolProgressEvent {
  version?: number;
  phase?: "start" | "end" | "error" | string;
  call_id?: string;
  name?: string;
  arguments?: unknown;
  result?: unknown;
  error?: unknown;
  files?: unknown[];
  embeds?: unknown[];
}

export interface ChatSummary {
  /** Server-side session key, e.g. ``websocket:abcd-...``. */
  key: string;
  /** Local channel + chat_id parts derived from ``key`` for convenience. */
  channel: string;
  chatId: string;
  createdAt: string | null;
  updatedAt: string | null;
  title?: string;
  preview: string;
}

export interface BootstrapResponse {
  token: string;
  ws_path: string;
  expires_in: number;
  model_name?: string | null;
}

export interface SettingsPayload {
  agent: {
    model: string;
    provider: string;
    resolved_provider: string | null;
    has_api_key: boolean;
  };
  providers: Array<{
    name: string;
    label: string;
    configured: boolean;
    api_key_hint?: string | null;
    api_base?: string | null;
    default_api_base?: string | null;
    model_catalog_kind?: "official" | "catalog" | "local" | "custom" | "unsupported";
  }>;
  web_search: {
    provider: string;
    api_key_hint?: string | null;
    base_url?: string | null;
    providers: Array<{
      name: string;
      label: string;
      credential: "none" | "api_key" | "base_url";
    }>;
  };
  learning: {
    background_review: {
      enabled: boolean;
    };
    curator?: {
      enabled: boolean;
    };
  };
  voice?: {
    input_enabled: boolean;
    output_enabled: boolean;
    transcription_enabled: boolean;
    tts_enabled: boolean;
    require_confirmation: boolean;
    save_dir: string;
    max_record_seconds: number;
    device_id?: string | null;
    voice?: string | null;
    transcription_provider: "groq" | "openai" | "volcengine" | string;
    transcription_language?: string | null;
    tts_provider?: string | null;
    transcription_provider_options?: string[];
  };
  runtime_controls: {
    channels: {
      send_progress: boolean;
      send_tool_hints: boolean;
      show_reasoning: boolean;
    };
    agent: {
      unified_session: boolean;
      cold_archive_enabled: boolean;
      allow_agent_initiated_messages: boolean;
      auxiliary_enabled: boolean;
      domain_packs_enabled: boolean;
      provider_retry_mode: string;
      dream_annotate_line_ages: boolean;
    };
    learning: {
      background_review_enabled: boolean;
      curator_enabled: boolean;
    };
    evolution: {
      mode: string;
      allow_manual_override: boolean;
      dry_run: boolean;
      outcome_archive_enabled: boolean;
      dependency_stale_cleanup_enabled: boolean;
      auto_verify_workflows: boolean;
      skill_candidates_enabled: boolean;
      feedback_calibration_enabled: boolean;
      sandbox_enabled: boolean;
      trial_enabled: boolean;
      trial_isolated_workspace: boolean;
      trial_read_only_tools_only: boolean;
    };
    gateway: {
      heartbeat_enabled: boolean;
    };
    security: {
      pairing_enabled: boolean;
      pairing_allow_self_approve: boolean;
    };
    search: {
      web_enabled: boolean;
      web_fetch_use_jina_reader: boolean;
      session_search_enabled: boolean;
      session_search_backend: string;
      session_search_semantic_enabled: boolean;
      session_search_rebuild_on_start: boolean;
      content_read_enabled: boolean;
      content_read_use_jina_reader: boolean;
    };
    execution: {
      exec_enabled: boolean;
      exec_profile: string;
      exec_allow_unsafe_exec: boolean;
      exec_shell_syntax_policy: string;
      my_enabled: boolean;
      my_allow_set: boolean;
      restrict_to_workspace: boolean;
    };
    media: {
      image_generation_enabled: boolean;
    };
    devices: {
      device_enabled: boolean;
      device_lighting_enabled: boolean;
      device_mode: string;
      device_backend: string;
    };
    subagent: {
      mode: "normal" | "restricted";
    };
    audit: {
      audit_mode: string;
      audit_security_on_policy_denial: boolean;
    };
    runtime: {
      profile: string;
    };
  };
  mcp: {
    servers: McpServerSettings[];
  };
  runtime: {
    config_path: string;
  };
  requires_restart: boolean;
}

export interface SettingsUpdate {
  model?: string;
  provider?: string;
}

export interface ProviderSettingsUpdate {
  provider: string;
  apiKey?: string;
  apiBase?: string;
  forceRefresh?: boolean;
}

export interface FetchedProviderModel {
  id: string;
  owned_by?: string | null;
}

export interface ProviderModelsResponse {
  provider: string;
  status: "available";
  catalog_kind: "official" | "catalog" | "local" | "custom" | "unsupported";
  models: FetchedProviderModel[];
  model_count: number;
  fetched_at: number;
  source_url?: string | null;
  cached?: boolean;
  phase?: "contract" | "fetch" | string;
}

export interface ProviderModelsErrorResponse {
  message: string;
  reason?: string;
  phase?: "contract" | "fetch" | string;
}

export interface WebSearchSettingsUpdate {
  provider: string;
  apiKey?: string;
  baseUrl?: string;
}

export interface VoiceSettingsUpdate {
  input_enabled?: boolean;
  output_enabled?: boolean;
  transcription_enabled?: boolean;
  tts_enabled?: boolean;
  require_confirmation?: boolean;
  save_dir?: string;
  max_record_seconds?: number;
  device_id?: string | null;
  voice?: string | null;
  transcription_provider?: string;
  transcription_language?: string | null;
}

export interface RuntimeSettingsUpdate {
  channels?: Partial<SettingsPayload["runtime_controls"]["channels"]>;
  agent?: Partial<SettingsPayload["runtime_controls"]["agent"]>;
  learning?: Partial<
    SettingsPayload["runtime_controls"]["learning"] & {
      meta_cognition_enabled?: boolean;
      meta_trigger_collection_enabled?: boolean;
      meta_structured_reflection_enabled?: boolean;
      meta_pattern_consolidation_enabled?: boolean;
      meta_evolution_bridge_enabled?: boolean;
      meta_working_memory_bridge_enabled?: boolean;
      meta_memory_candidate_bridge_enabled?: boolean;
    }
  >;
  evolution?: Partial<SettingsPayload["runtime_controls"]["evolution"]>;
  gateway?: Partial<SettingsPayload["runtime_controls"]["gateway"]>;
  security?: Partial<SettingsPayload["runtime_controls"]["security"]>;
  search?: Partial<SettingsPayload["runtime_controls"]["search"]>;
  execution?: Partial<SettingsPayload["runtime_controls"]["execution"]>;
  media?: Partial<SettingsPayload["runtime_controls"]["media"]>;
  devices?: Partial<SettingsPayload["runtime_controls"]["devices"]>;
  subagent?: Partial<SettingsPayload["runtime_controls"]["subagent"]>;
  audit?: Partial<SettingsPayload["runtime_controls"]["audit"]>;
  runtime?: Partial<SettingsPayload["runtime_controls"]["runtime"]>;
}

export type McpTransportType = "stdio" | "sse" | "streamableHttp";

export interface McpServerSettings {
  name: string;
  type?: McpTransportType | null;
  command: string;
  args: string[];
  env: Record<string, string>;
  url: string;
  headers: Record<string, string>;
  tool_timeout: number;
  enabled_tools: string[];
}

export interface McpServerSettingsUpdate {
  name: string;
  type?: McpTransportType | null;
  command?: string;
  args?: string[];
  env?: Record<string, string>;
  url?: string;
  headers?: Record<string, string>;
  tool_timeout?: number;
  enabled_tools?: string[];
}

export interface HomeAssistantMcpSettingsUpdate {
  name: string;
  address: string;
  token?: string;
}

export interface SlashCommand {
  command: string;
  title: string;
  description: string;
  icon: string;
  argHint?: string;
}

export type ReviewProposalStatus = "pending" | "applied" | "rejected" | "deferred" | "failed";
export type ReviewProposalType = "memory" | "fact" | "skill" | "workflow" | string;
export type ReviewProposalOrigin = "background_review" | "curator" | "auto_evolution" | string;

// ── Meta-Cognition Types ──────────────────────────────────────────

export interface MetaTriggerRecord {
  trigger_id: string;
  session_key: string;
  trigger_type: "tool_failure" | "user_correction" | "task_completion";
  source_type: string;
  source_reference: string;
  severity: "low" | "medium" | "high";
  created_at: string;
  cooldown_key?: string;
  evidence_refs?: string[];
  payload: Record<string, unknown>;
}

export interface ReflectionRecord {
  reflection_id: string;
  session_key: string;
  summary: string;
  reflection_kind: string;
  outcome_class: string;
  root_cause_hypotheses?: string[];
  what_worked?: string[];
  what_failed?: string[];
  learned_rule_candidate?: Record<string, unknown> | null;
  confidence: number;
  retention_hint: string;
  created_at?: string;
  payload?: Record<string, unknown>;
}

export interface PatternRecord {
  pattern_id: string;
  pattern_key: string;
  owner_id: string;
  trigger_types: string[];
  capability_domain: string;
  severity: "low" | "medium" | "high";
  frequency: number;
  distinct_turn_count: number;
  pattern_score: number;
  candidate_target_type: string | null;
  summary: string;
  created_at?: string;
  updated_at?: string;
  recency_score?: number;
  example_refs?: string[];
}

export interface BridgeDecisionCounts {
  [key: string]: number;
}

export interface BridgeStatus {
  enabled: boolean;
  last_status: string;
  decision_counts: BridgeDecisionCounts;
}

export interface UncertaintyStats {
  avg: number;
  max: number;
  high_count: number;
  threshold: number;
}

export interface RuntimeStatus {
  accepted_total: number;
  suppressed_total: number;
}

export interface ArtifactStatus {
  journals_written?: number;
  reflections_written?: number;
  confidence_traces_written?: number;
  patterns_written?: number;
  evolution_seeds_written?: number;
  working_memory_bridge?: BridgeStatus;
  memory_candidate_bridge?: BridgeStatus;
}

export interface MetaCognitionSummary {
  contract_version: string;
  enabled: boolean;
  trigger_collection_enabled: boolean;
  structured_reflection_enabled: boolean;
  pattern_consolidation_enabled: boolean;
  evolution_bridge_enabled: boolean;
  runtime_status: RuntimeStatus;
  recent_triggers: MetaTriggerRecord[];
  recent_decisions: Record<string, unknown>[];
  recent_journals: Record<string, unknown>[];
  recent_reflections: ReflectionRecord[];
  recent_confidence_traces: Record<string, unknown>[];
  recent_patterns: PatternRecord[];
  recent_evolution_seeds: Record<string, unknown>[];
  decision_counts: Record<string, number>;
  suppression_reason_counts: Record<string, number>;
  uncertainty_stats: UncertaintyStats;
  artifact_status: ArtifactStatus;
  working_memory_bridge: BridgeStatus;
  memory_candidate_bridge: BridgeStatus;
  bridge_decision_counts: BridgeDecisionCounts;
  pattern_counts: Record<string, number>;
  seed_counts: Record<string, number>;
  last_signal_upserts: Record<string, unknown>[];
  fast_path_decision_counts: BridgeDecisionCounts;
}

export interface EvidenceSource {
  cursor: string | null;
  session_key: string;
  timestamp: string;
  preview: string;
}

export interface OpportunitySignal {
  opportunity_id: string;
  kind: "workflow_candidate" | "skill_candidate";
  target_key: string;
  title: string;
  summary: string;
  source_pattern_id: string;
  evidence_sources: EvidenceSource[];
  first_seen_at: string;
  last_seen_at: string;
  seen_count: number;
  priority_score: number;
  risk_level: string;
  status: "open" | "converted" | "suppressed";
  converted_proposal_id: string | null;
  verification_status?: string;
  feedback_multiplier?: number;
  feedback_negative_count?: number;
  feedback_positive_count?: number;
  suppression_reason?: string;
}

export interface EvolutionStatus {
  mode: string;
  dry_run: boolean;
  opportunity_signals_count: number;
  eligible_workflow_signals: number;
  eligible_skill_signals: number;
  converted_signals_count: number;
  suppressed_signals_count: number;
  feedback_adjusted_signals_count: number;
  high_score_signals: Array<{
    kind: string;
    target: string;
    priority_score: number;
  }>;
  skill_candidates_enabled: boolean;
  pending_proposals_from_evolution: number;
}

export interface ReviewProposalEvent {
  event_id?: string;
  proposal_id?: string;
  status?: ReviewProposalStatus | string;
  created_at?: string;
  reason?: string;
  fact_id?: string | null;
  skill_name?: string | null;
  skill_path?: string | null;
  workflow_name?: string | null;
  workflow_path?: string | null;
  artifact?: ReviewApplyArtifact | null;
  error?: string;
}

export interface ReviewApplyArtifact {
  artifact_type?: "skill" | "workflow" | string;
  skill_name?: string;
  workflow_name?: string;
  path?: string;
  validation?: string;
}

export interface ReviewProposal {
  id: string;
  created_at?: string;
  session_key?: string;
  turn_id?: string;
  origin?: ReviewProposalOrigin;
  proposal_type: ReviewProposalType;
  domain_id?: string;
  title: string;
  content: string;
  rationale?: string;
  confidence?: number | null;
  evidence?: string[];
  payload?: Record<string, unknown>;
  source_message_id?: string | null;
  status: ReviewProposalStatus | string;
  review_reason?: string;
  applied_fact_id?: string;
  applied_skill_name?: string;
  applied_skill_path?: string;
  applied_workflow_name?: string;
  applied_workflow_path?: string;
  apply_artifact?: ReviewApplyArtifact;
  can_apply?: boolean;
  unsupported_reason?: string;
  subject_label?: string;
  suggested_action?: string;
  review_only?: boolean;
  review_event?: ReviewProposalEvent;
}

export interface ReviewProposalStats {
  proposal_count: number;
  pending_count: number;
  last_created_at: string | null;
}

export interface ReviewDecisionResult {
  proposal_id: string;
  status: ReviewProposalStatus | string;
  action: string;
  ok: boolean;
  message: string;
  proposal?: ReviewProposal | null;
  event?: ReviewProposalEvent | null;
  fact_id?: string | null;
  artifact?: ReviewApplyArtifact | null;
  error?: string;
}

export type SkillLifecycleStatus = "proposed" | "active" | "deprecated" | "rejected" | string;
export type SkillVerificationStatus = "unverified" | "verified" | "rejected" | "unknown" | string;

export interface SkillRecord {
  name: string;
  path: string;
  source: string;
  description?: string;
  body_preview?: string;
  proposal_status?: string;
  verification_status: SkillVerificationStatus;
  lifecycle_status: SkillLifecycleStatus;
  version?: string;
  supersedes_skill?: string;
  reviewed_by?: string;
  reviewed_at?: string;
  review_proposal_id?: string;
  domain_id?: string;
  created_by?: string;
  last_lifecycle_event_id?: string;
  always?: boolean;
  effective_always?: boolean;
  can_manage_lifecycle?: boolean;
  disabled_reason?: string;
  can_verify?: boolean;
  can_activate?: boolean;
  can_deprecate?: boolean;
  can_reject?: boolean;
  can_toggle_always?: boolean;
  last_event?: Record<string, unknown> | null;
}

export interface SkillLifecycleStats {
  skills_count: number;
  workspace_skills_count: number;
  skill_lifecycle_status_counts: Record<string, number>;
  skill_verification_status_counts: Record<string, number>;
  unverified_skill_count: number;
  deprecated_skill_count: number;
  rejected_skill_count: number;
  always_workspace_skill_count: number;
}

export interface SkillLifecycleResult {
  skill_name: string;
  status: SkillLifecycleStatus;
  action: string;
  ok: boolean;
  message: string;
  skill?: SkillRecord | null;
  event?: Record<string, unknown> | null;
  error?: string;
}

export interface DomainDeclarationRecord {
  id: string;
  path?: string;
  status: string;
  unavailable_reason?: string;
  virtual_id?: string;
  module?: string;
  class_name?: string;
  permissions?: string[];
  audit?: string;
  target?: string;
  kind?: string;
}

export interface DomainPackRecord {
  id: string;
  name: string;
  version: string;
  path: string;
  source: string;
  status: string;
  enabled: boolean;
  active: boolean;
  active_requested?: boolean;
  verification_status: string;
  overrides_builtin?: boolean;
  description?: string;
  validation_summary?: string;
  unavailable_reason?: string;
  capabilities?: string[];
  triggers?: string[];
  dependencies?: { packs: string[] };
  source_info?: {
    kind: "builtin" | "local_copy";
    installed_from?: string;
    installed_at?: string;
  };
  skills?: DomainDeclarationRecord[];
  workflows?: DomainDeclarationRecord[];
  policies?: DomainDeclarationRecord[];
  schemas?: DomainDeclarationRecord[];
  tools?: DomainDeclarationRecord[];
  evals?: DomainDeclarationRecord[];
  can_install?: boolean;
  can_upgrade?: boolean;
  can_uninstall?: boolean;
  can_enable?: boolean;
  can_disable?: boolean;
  can_activate?: boolean;
  can_deactivate?: boolean;
  can_eval?: boolean;
  disabled_reason?: string;
  last_event?: Record<string, unknown> | null;
  last_eval_result?: {
    ok?: boolean;
    status?: string;
    checks?: Array<Record<string, unknown>>;
    warnings?: string[];
    errors?: string[];
    pack?: string;
  } | null;
}

export interface DomainPackGovernanceStats {
  workspace_domain_pack_count: number;
  builtin_domain_pack_count: number;
  domain_pack_status_counts: Record<string, number>;
  active_domain_pack_count: number;
  domain_pack_override_count: number;
  domain_pack_eval_status_counts: Record<string, number>;
  last_domain_pack_event_at: string | null;
}

export interface DomainPackGovernanceResult {
  pack_id: string;
  status: string;
  action: string;
  ok: boolean;
  message: string;
  pack?: DomainPackRecord | null;
  event?: Record<string, unknown> | null;
  eval_result?: {
    ok?: boolean;
    status?: string;
    checks?: Array<Record<string, unknown>>;
    warnings?: string[];
    errors?: string[];
    pack?: string;
  } | null;
  artifact?: ReviewApplyArtifact | null;
  error?: string;
}

export interface WorkflowArtifactRecord {
  name: string;
  path: string;
  status: string;
  proposal_status: string;
  verification_status: string;
  domain_id: string;
  managed_by_domain_pack: boolean;
  unavailable_reason?: string;
}

export interface SelfModelLimitation {
  code: string;
  status: "info" | "warning" | "error" | string;
  subject_type: string;
  subject_id: string;
  summary: string;
}

export interface SelfModel {
  schema_version: number;
  generated_at: string;
  identity: {
    agent_name: string;
    workspace_name: string;
    runtime_profile: string;
    audit_mode: string;
  };
  runtime: {
    registered_tools_count: number;
    active_sessions_count: number;
    pending_queue_count: number;
    cron_available: boolean;
    confirmation_available: boolean;
    background_review_enabled: boolean;
    curator_enabled: boolean;
  };
  domains: {
    stats: DomainPackGovernanceStats;
    items: DomainPackRecord[];
  };
  skills: {
    stats: SkillLifecycleStats;
    items: SkillRecord[];
  };
  workflows: {
    stats: {
      workflow_artifacts_count: number;
      workflow_artifact_status_counts: Record<string, number>;
      invalid_workflow_artifacts_count: number;
      workflow_status_counts: Record<string, number>;
      workflow_verification_status_counts: Record<string, number>;
      managed_by_domain_pack_count: number;
    };
    items: WorkflowArtifactRecord[];
  };
  facts: {
    active_count: number;
    pending_confirmation_count: number;
    category_counts: Record<string, number>;
    domain_counts: Record<string, number>;
  };
  memory: {
    has_memory_context: boolean;
    recent_history_pending_count: number;
  };
  reviews: {
    pending_count: number;
    status_counts: Record<string, number>;
    type_counts: Record<string, number>;
    origin_counts: Record<string, number>;
  };
  confirmations: {
    pending_count: number;
    expired_count: number;
    kind_counts: Record<string, number>;
    risk_counts: Record<string, number>;
  };
  limitations: SelfModelLimitation[];
}

export type ConnectionStatus =
  | "idle"
  | "connecting"
  | "open"
  | "reconnecting"
  | "closed"
  | "error";

export type InboundEvent =
  | { event: "ready"; chat_id: string; client_id: string }
  | { event: "attached"; chat_id: string }
  | {
      event: "message";
      chat_id: string;
      text: string;
      reply_to?: string;
      media?: string[];
      media_urls?: Array<{ url: string; name?: string }>;
      tool_events?: ToolProgressEvent[];
      buttons?: string[][];
      /** Original prompt before the websocket text fallback appends buttons. */
      button_prompt?: string;
      /** Present when the frame is an agent breadcrumb (e.g. tool hint,
       * generic progress line) rather than a conversational reply. */
      kind?: "tool_hint" | "progress" | "reasoning";
      /** Server-measured turn wall time when this frame finishes an assistant reply. */
      latency_ms?: number;
      /** Optional structured payload on progress frames (channel-specific). */
      agent_ui?: AgentUIBlob;
    }
  | {
      event: "delta";
      chat_id: string;
      text: string;
      stream_id?: string;
    }
  | {
      event: "stream_end";
      chat_id: string;
      stream_id?: string;
    }
  | {
      event: "reasoning_delta";
      chat_id: string;
      text: string;
      stream_id?: string;
    }
  | {
      event: "reasoning_end";
      chat_id: string;
      stream_id?: string;
    }
  | {
      event: "runtime_model_updated";
      model_name: string;
      model_preset?: string | null;
    }
  | {
      event: "turn_end";
      chat_id: string;
      latency_ms?: number;
      /** Authoritative sustained-goal snapshot for this chat (same shape as ``goal_state`` events). */
      goal_state?: GoalStateWsPayload;
    }
  | {
      event: "goal_status";
      chat_id: string;
      /** Turn executing (user message through agent loop). */
      status: "running" | "idle";
      /** Server ``time.time()`` when ``status`` is ``running``. */
      started_at?: number;
    }
  | {
      event: "goal_state";
      chat_id: string;
      goal_state: GoalStateWsPayload;
    }
  | { event: "session_updated"; chat_id: string }
  | { event: "error"; chat_id?: string; detail?: string; reason?: string };

/** Base64-encoded attachment attached to an outbound ``message`` envelope.
 *
 * ``data_url`` must be a supported ``data:<mime>;base64,...`` string. The
 * server applies a conservative MIME whitelist and per-kind limits; unsupported
 * types are rejected before the turn reaches the Agent runtime. ``name`` is
 * advisory: it's preserved for the file on disk and surfaced during replay.
 */
export interface OutboundMedia {
  data_url: string;
  name?: string;
}

export interface OutboundImageGeneration {
  enabled: true;
  aspect_ratio?: string | null;
}

/** Response shape for ``GET .../webui-thread`` (server-built transcript replay). */
export interface WebuiThreadPersistedPayload {
  schemaVersion: number;
  sessionKey?: string;
  savedAt?: string;
  messages: UIMessage[];
}

export type Outbound =
  | { type: "new_chat" }
  | { type: "attach"; chat_id: string }
  | {
      type: "message";
      chat_id: string;
      content: string;
      media?: OutboundMedia[];
      image_generation?: OutboundImageGeneration;
      /** Marks messages sent by the embedded WebUI, without changing the
       * generic websocket protocol for other clients. */
      webui?: true;
      /** Current UI language code (e.g. "zh-CN", "ja") so the server
       * can localise slash-command responses. */
      lang?: string;
    };


